apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f infra/docker-compose.yml -o infra/k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: configdb-replica0
  name: configdb-replica0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: configdb-replica0
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f infra/docker-compose.yml -o infra/k8s
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/infra-internalnetwork: "true"
        io.kompose.service: configdb-replica0
    spec:
      containers:
        - args:
            - mongod
            - -f
            - /etc/mongod.conf
            - --configsvr
            - --replSet
            - configdb
          env:
            - name: DO_INIT_REPSET
              value: "true"
            - name: REPSET_NAME
              value: configdb
          image: mongod:latest
          imagePullPolicy: Never
          name: configdb-replica0
          ports:
            - containerPort: 27017
          resources: {}

      restartPolicy: Always

status: {}
