"""initial migration

Revision ID: 2801295852f4
Revises: 
Create Date: 2023-04-30 21:05:40.199238

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2801295852f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(sa.schema.CreateSchema("shopper"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["shopper.category.id"],
            name=op.f("fk__category__category__parent_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__category__id")),
        schema="shopper",
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user__id")),
        schema="shopper",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user", schema="shopper")
    op.drop_table("category", schema="shopper")
    # ### end Alembic commands ###

    op.execute(sa.schema.DropSchema("shopper"))
