"""add role table, add user_role table

Revision ID: 6861747480bc
Revises: 3a794e77645e
Create Date: 2023-05-20 11:45:27.918745

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6861747480bc"
down_revision = "3a794e77645e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__role__id")),
        schema="shopper",
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["shopper.role.id"],
            name=op.f("fk__user_role__role__role_id"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["shopper.user.id"],
            name=op.f("fk__user_role__user__user_id"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "role_id",
            name=op.f("pk__user_role__user_id_role_id"),
        ),
        schema="shopper",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_role", schema="shopper")
    op.drop_table("role", schema="shopper")
    # ### end Alembic commands ###
