"""add product table

Revision ID: 71cd8c7135b8
Revises: 2801295852f4
Create Date: 2023-05-01 15:25:33.701042

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "71cd8c7135b8"
down_revision = "2801295852f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "price",
            sa.Numeric(precision=18, scale=2, asdecimal=False),
            nullable=False,
        ),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["shopper.category.id"],
            name=op.f("fk__product__category__category_id"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__product__id")),
        schema="shopper",
    )
    op.add_column(
        "category",
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="shopper",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "metadata", schema="shopper")
    op.drop_table("product", schema="shopper")
    # ### end Alembic commands ###
