"""add username

Revision ID: f245daf5f54f
Revises: 71cd8c7135b8
Create Date: 2023-05-03 20:17:25.456384

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f245daf5f54f"
down_revision = "71cd8c7135b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("username", sa.String(length=255), nullable=False),
        schema="shopper",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "username", schema="shopper")
    # ### end Alembic commands ###
