version: '3.9'

services:
    app:
        image: 'app:latest'
        container_name: shopper_backend
        build:
            context: app/
        ports:
            - 8080:8080
        volumes:
            - ./.env:/app/.env:ro

        entrypoint:
            [
                "uvicorn",
                "src.main:app",
                "--port",
                "8080",
                "--host",
                "0.0.0.0"
            ]
    postgres:
        image: postgres:15.2-alpine
        container_name: shopper_postgres
        ports:
            - 5432:5432

        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DATABASE=${DB_NAME}

    shard0-replica0:
        build:
            context: mongod
        command: mongod -f /etc/mongod.conf --shardsvr --replSet shard0
        volumes:
            - ./mongod/mongod.conf:/etc/mongod.conf
        networks:
            internalnetwork:
                aliases:
                    - shard0-replica0
        environment:
            - REPSET_NAME=shard0
            - DO_INIT_REPSET=true
        expose:
            - "27017"

    shard0-replica1:
        build:
            context: mongod
        command: mongod -f /etc/mongod.conf --shardsvr --replSet shard0
        volumes:
            - ./mongod/mongod.conf:/etc/mongod.conf
        networks:
            internalnetwork:
                aliases:
                    - shard0-replica1
        environment:
            - REPSET_NAME=shard0
        expose:
            - "27017"

    shard1-replica0:
        build:
            context: mongod
        command: mongod -f /etc/mongod.conf --shardsvr --replSet shard1
        volumes:
            - ./mongod/mongod.conf:/etc/mongod.conf
        networks:
            internalnetwork:
                aliases:
                    - shard1-replica0
        environment:
            - REPSET_NAME=shard1
            - DO_INIT_REPSET=true
        expose:
            - "27017"

    shard1-replica1:
        build:
            context: mongod
        command: mongod -f /etc/mongod.conf --shardsvr --replSet shard1
        volumes:
            - ./mongod/mongod.conf:/etc/mongod.conf
        networks:
            internalnetwork:
                aliases:
                    - shard1-replica1
        environment:
            - REPSET_NAME=shard1
        expose:
            - "27017"

    configdb-replica0:
        build:
            context: mongod
        command: mongod -f /etc/mongod.conf --configsvr --replSet configdb
        volumes:
            - ./mongod/mongod.conf:/etc/mongod.conf
        networks:
            internalnetwork:
                aliases:
                    - configdb-replica0
        environment:
            - REPSET_NAME=configdb
            - DO_INIT_REPSET=true
        expose:
            - "27017"

    configdb-replica1:
        build:
            context: mongod
        command: mongod -f /etc/mongod.conf --configsvr --replSet configdb
        volumes:
            - ./mongod/mongod.conf:/etc/mongod.conf
        networks:
            internalnetwork:
                aliases:
                    - configdb-replica1
        environment:
            - REPSET_NAME=configdb
        expose:
            - "27017"

    mongos-router:
        build:
            context: mongos
        command: mongos --port 27017 --bind_ip 0.0.0.0 --configdb "configdb/configdb-replica0:27017,configdb-replica1:27017"
        depends_on:
            - shard0-replica0
            - shard0-replica1
            - shard1-replica0
            - shard1-replica1
            - configdb-replica0
            - configdb-replica1
        networks:
            internalnetwork:
                aliases:
                    - mongos-router
        environment:
            - SHARD_LIST=shard0/shard0-replica0:27017,shard0-replica1:27017;shard1/shard1-replica0:27017,shard1-replica1:27017
        expose:
            - "27017"
        ports:
            - "27017:27017"

networks:
    internalnetwork: {}
