version: '3.9'

services:
    app:
        image: 'app:latest'
        container_name: shopper_backend
        build: .
        ports:
            - ${APP_PORT}:${APP_PORT}
        volumes:
            - ./.env:/app/.env:ro

        entrypoint: ["uvicorn", "src.main:app", "--port", "${APP_PORT}", "--host", "0.0.0.0"]


    postgres:
        image: postgres:15.2-alpine
        container_name: shopper_postgres
        ports:
            - 5432:5432

        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DATABASE=${DB_NAME}
