apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s-new/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-master
  name: postgres-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s-new/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/infra-default: "true"
        io.kompose.service: postgres-master
    spec:
      containers:
        - image: docker.io/bitnami/postgresql:15.3.0-debian-11-r4
          name: shopper-postgres-master
          env:
            - name: POSTGRESQL_PGAUDIT_LOG
              value: READ,WRITE
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "true"
            - name: POSTGRESQL_REPLICATION_MODE
              value: master
          envFrom:
            - secretRef:
                name: postgres-secrets

          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume
      restartPolicy: Always
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-volume
status: {}
